project:
  type: website
  title: "Introduction to R Statistical Analysis Software"
  output-dir: docs
  render:
    - index.qmd
    - data.qmd
    - about.qmd
    - materials.qmd
    - recommended.qmd


website:
  title: "Introduction to R Statistical Analysis Software"
  description: "Homepage for R - Review course in APEC at the University of Minnesota, Summer 2024."
  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/Shunkei3/R-2024-Summer
        # text: GitHub
  sidebar:
    style: "docked"
    search: true
    # logo: "images/logo.png"
    # pinned: true
    # align: center
    contents:
      - href: index.qmd
        text: Syllabus
      - href: about.qmd
        text: Schedule
      - href: data.qmd
      - href: materials.qmd
      - href: recommended.qmd
    page-navigation: true

format:
  html:
    theme: 
      # cosmo
      light: [cosmo, flatly, assets/css/theme.scss]
      dark: [cosmo, darkly]
    css: styles.css
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

callout-appearance: simple

execute:
  freeze: auto