project:
  type: website
  title: "Introduction to R Statistical Analysis Software"
  output-dir: docs
website:
  title: "Introduction to R Statistical Analysis Software"
  description: "Homepage for R - Review course in APEC at the University of Minnesota, Summer 2024."
  google-analytics: "'G-2CNBSQRRD2'"
  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/Shunkei3/R-2024-Summer
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - text: Syllabus
        href: contents/index.qmd
      - text: Schedule
        href: contents/plan.qmd
      - section: "Class Materials"
        contents:
          - href: contents/day1.qmd
          - href: contents/day2.qmd
          - href: contents/day3.qmd
          - href: contents/day4.qmd
          - href: contents/day5.qmd
          - href: contents/data.qmd
      - section: "Appendix"
        contents:
          - text: "Useful shorcut keys in the Rstudio"
            href: contents/Apx1.qmd
          - text: "Rmarkdown for making a PDF document"
            href: contents/Apx2.qmd
          - text: "LaTex Mathematical Expressions"
            href: contents/Apx3.qmd
          - text: "Introduction to Quarto"
            href: contents/Apx4.qmd
      - href: contents/recommended.qmd
    page-navigation: true

format:
  html:
    theme: 
      # cosmo
      light: [cosmo, flatly, assets/css/theme.scss]
      dark: [cosmo, darkly,  assets/css/theme.scss]
    # css: styles.css
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

# callout-appearance: simple

execute:
  freeze: auto