project:
  type: website
  title: "Introduction to R Statistical Analysis Software"
  output-dir: docs

website:
  title: "Introduction to R Statistical Analysis Software (2024-Summer)"
  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/Shunkei3/R-2024-Summer
        # text: GitHub
  sidebar:
    style: "docked"
    search: true
    # logo: "images/logo.png"
    # pinned: true
    # align: center
    contents:
      - href: index.qmd
        text: Home
      - href: data.qmd
      - href: materials.qmd
    page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

callout-appearance: simple


execute:
  freeze: auto