---
title: Appendix
---

### LaTeX Mathematical Symbols

{{< fa file >}} [Latex math notations and Example R codes with PDF output](https://shunkei3.github.io/R-slides/z_doc/Demonstration.pdf){target="_blank"}

In this document, you can find the list of basic LaTeX commands and exmaple codes to write mathematical equations, which might be useful if you are not familiar with LaTeX. 

<br>

### Rmarkdown for PDF

{{< fa file >}} Template Rmarkdown document for PDF output: [Download from here](https://shunkei3.github.io/R-slides/z_doc/templated_for_pdf.Rmd)

+ The output looks like [this](https://shunkei3.github.io/R-slides/z_doc/templated_for_pdf.pdf){target="_blank"}.


:::{.solutionbox}
::::{.solutionbox-header}
:::: {.solutionbox-icon}
::::
Before createing PDF documents from R Markdown
::::
:::{.solutionbox-body}
Before render R Markdown documents to PDF on your Rstudio, make sure that your computer has a LaTeX distribution installed. You can download and install the TinyTeX distribution with the R package [`tinytex`](https://yihui.org/tinytex/). Unlike other LaTex distributions like MacTeX, `tinytex` is a lightweight distribution that only includes the essential packages needed to render R Markdown documents to PDF.

```r
tinytex::install_tinytex()
# to uninstall TinyTeX, run
# tinytex::uninstall_tinytex()
```

Reference: "R Markdown Cookbook" by Yihui Xie, Christophe Dervieux, and Emily Riederer [[here](https://bookdown.org/yihui/rmarkdown-cookbook/)]
:::
:::





<br>

### Quarto

{{< fa link >}} How to use Quarto in Rstudio? Follow [this tutorial](https://quarto.org/docs/get-started/hello/rstudio.html)!

{{< fa file >}} [Quarto document Cheet Sheet](https://rstudio.github.io/cheatsheets/quarto.pdf)



