---
title: "Day 2: Data Wrangling with the `data.table` package"
---


The R package `data.table` is an extension of the `data.frame` class and is equipped with lots of additional powerful functionalities designed to handle large datasets. It is built for speed and efficiency. Unlike functions of the `dplyr` package (another popular R package for data wrangling), in which you need to use a specific function for each task, the syntax of `data.table` is so simple and consistent that you can do almost everything with just a few commands. 

In this lecture, we will learn the basic data wrangling skills with the `data.table` package. In addition, I will also briefly introduce the `%>%` operator of the `magrittr` package as a tool to make your code more concise and readable.

<br>

:::{.goals}
::::{.goals-header}
Learning Objectives
::::
::::{.goals-container}
+ To be able to use the basic data wrangling skills with the `data.table` package:
  + subset rows
  + select and compute on columns
  + rename columns
  + perform aggregations by group
  + merge multiple datasets
  + reshape wide-to-long and long-to-wide, respectively
+ to be able to use `%>%` operator of the `magrittr` package.
::::
:::

<br>

### Preparation
+  {{< fa file >}} [This](https://rdatatable.gitlab.io/data.table/) is the official website for the `data.table` package. Specifically, I recommend you take a look at the Introduction section.
+ {{< fa file >}} [Section 18: Pipes](https://r4ds.had.co.nz/pipes.html) in the book of R for Data Science is a good introduction to the `%>%` operator of the `magrittr` package.

<br>

### Lecture Slides
{{< fa laptop-code >}}  Click [here](https://shunkei3.github.io/R-slides/Lec_notes/Lec2/Lec2.html){target="_blank"} for Lecture 2's slides.

{{< fa file >}} [Exercise problems](https://shunkei3.github.io/R-slides/Lec_notes/Lec2/Lec2_exercise_solution.html){target="_blank"}: Exercise problems for Lecture 2. Solution is attached.

Quick view of the slides:


```{=html}
<div style="display: flex; justify-content: center;"> 
<iframe width="900" height="600" src="https://shunkei3.github.io/R-slides/Lec_notes/Lec2/Lec2.html" title="Webpage example"></iframe>
</div>
```

<br>

### Supplementary Materials

{{< fa file >}} [`data.table` homepage](https://rdatatable.gitlab.io/data.table/){target="_blank"}. 

{{< fa file >}} [Using .SD for Data Analysis](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-sd-usage.html){target="_blank"} (Although we will not cover this topic in the class, it would be useful if you know how to use `.SD` in data.table.)

The `data.table` package supports multithreading, allowing it to efficiently handle large datasets utilizing multiple CPU cores simultaneously. To set up multithreading in `data.table`, you need to do some configuration on your computer a bit (at least for Mac users). Follow {{< fa newspaper >}} [this instruction](https://github.com/Rdatatable/data.table/wiki/Installation#linux-and-mac){target="_blank"}. 

<!-- :::{.solutionbox}

::::{.solutionbox-header}
:::: {.solutionbox-icon}
::::
This is my test note
::::

:::{.solutionbox-body}
Add some content inside of it
:::

::: -->

