---
title: "Day 4: Introduction to Regression Analysis in R (Under Construction)"
---

In this lecture, we will learn how to use the `lm()` function to conduct regression analysis in R. To report the regression result with a table, we will use the `modelsummary()` function of the `modelsummary` package. 


<br>

:::{.goals}
::::{.goals-header}
Learning Objectives
::::
::::{.goals-container}
+ to be able to use the `lm()` function to conduct regression analysis in R.
+ to be able to create a summary table of regression results with the `modelsummary()` function.
+ to be able to create a summary table of descriptive statistics with the `datasummary()` function.
::::
:::

<br>

### Preparation
+ [This](https://modelsummary.com/) is the official website for the `modelsummary` package. Let's take a look at the website and see what kind of tables you can create with the `modelsummary` package.

<br>

### Lecture Slides

{{< fa laptop-code >}}  Click [here](https://shunkei3.github.io/R-slides/Lec_notes/Lec4/Lec4.html){target="_blank"} for Lecture 4's slides.

{{< fa file >}} [Exercise problems](https://shunkei3.github.io/R-slides/Lec_notes/Lec1/Lec1_exercise_solution.html){target="_blank"}: Exercise problems for Lecture 4. Solution is attached.

<br>

Quick view of the lecture slides:

```{=html}
<div style="display: flex; justify-content: center;"> 
<iframe width="900" height="600" src="https://shunkei3.github.io/R-slides/Lec_notes/Lec4/Lec4.html" title="Webpage example"></iframe>
</div>
```
<br>


### Supplementary Materials
+ Exercise Problems
+ Solutions for the Exercise Problems
+ For the estimation of fixed-effects model, you can use the [`fixest` package](https://lrberge.github.io/fixest/index.html).
