---
title: "Day 5: Functions, Loops, and Monte Carlo Simulations"
---

Monte Carlo simulations are potent tools in Econometrics and Statistics. From the student's perspective, they are helpful in understanding statistical and econometric theories, properties of the various estimators, and inference techniques. This class will teach you how to write R code to conduct Monte Carlo simulations. 

### Learning Objectives

:::{.goals}
::::{.goals-header}
Learning Objectives
::::
::::{.goals-container}
+ To be abel to write your own R functions.
+ To be able to use `for loop` function.
+ To be able to write R code for simple Monte Carlo Simulations to test statistical properties. 
::::
:::


### Preparation
Take a look at the following sections in the book of R for Data Science:

+ [Section 19 Functions](https://r4ds.had.co.nz/functions.html)
+ [Section 20 Iteration](https://r4ds.had.co.nz/iteration.html)


### Lecture Slides

{{< fa laptop-code >}}  Click [here](https://shunkei3.github.io/R-slides/Lec_notes/Lec5/Lec5.html){target="_blank"} for Lecture 5's slides.

{{< fa file >}} [Exercise problems](https://shunkei3.github.io/R-slides/Lec_notes/Lec5/Lec5_exercise_solutions.html){target="_blank"}: Exercise problems for Lecture 5. Solution is attached.

<br>

Quick view of the lecture slides:


```{=html}
<div style="display: flex; justify-content: center;"> 
<iframe width="900" height="600" src="https://shunkei3.github.io/R-slides/Lec_notes/Lec5/Lec5.html" title="Webpage example"></iframe>
</div>
```

### Supplementary Materials
+ Exercise Problems
+ Solutions for the Exercise Problems




