---
title: "Recommended Textbooks"
---

Below is the recommendation for reference. All the materials are freely available online. 


## Textbooks

{{< fa solid book >}} **[R for Data Science 2nd edition](https://r4ds.hadley.nz){target="_blank"} and [Solutions to Exercises](https://mine-cetinkaya-rundel.github.io/r4ds-solutions/){target="_blank"}**

This book mainly uses the `dplyr` package, which we do not cover in this course (Instead, we use `data.table` package.) But still, some chapters are highly useful for learning the basics of R. Specifically, take a look at the following chapters:

+ [Chapter 2 Workflow: basics](https://r4ds.hadley.nz/workflow-basics){target="_blank"}
+ [Chapter 6  Workflow: scripts and projects](https://r4ds.hadley.nz/workflow-scripts){target="_blank"}
+ [Chapter 25  Functions](https://r4ds.hadley.nz/functions){target="_blank"}
+ [Chapter 26  Iteration](https://r4ds.hadley.nz/iteration){target="_blank"}
+ [Chapter 27 A field guide to base R](https://r4ds.hadley.nz/base-r){target="_blank"}

<br>

{{< fa solid book >}} **[Introduction to data.table](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html){target="_blank"}**

I highly recommend this as an introduction to data.table syntax.

{{< fa solid book >}} **[ggplot2: Elegant Graphics for Data Analysis (3e)](https://ggplot2-book.org/){target="_blank"}**

{{< fa solid book >}} **[Modern Data Visualization with R by Robert Kabacoff](https://rkabacoff.github.io/datavis/){target="_blank"}**

{{< fa solid book >}} **[Matloff, Norman. The art of R programming: A tour of statistical software design. No Starch Press, 2011.](https://diytranscriptomics.com/Reading/files/The%20Art%20of%20R%20Programming.pdf){target="_blank"}**

The Programming for Econometrics class uses this book.


## Syntax Cheat Sheets



{{< fa file >}} [Data Transformation with data.table](https://raw.githubusercontent.com/rstudio/cheatsheets/master/datatable.pdf){target="_blank"}




